# version: "1"  # 작성하는 파일 버전
# services:  # container를 정의하는 자리
#   mysql000ex11:  # container1의 이름
#     image: mysql:8.0.29
#     networks:  # network를 정의하는 자리
#       - wordpress000net1
#     volumes:  # volume을 정의하는 자리
#       - mysql000vol11:/var/lib/mysql
#     restart: always  # 서버가 꺼지면 재시작
#     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
#     environment:  
#       MYSQL_ROOT_PASSWORD: myrootpass
#       MYSQL_DATABASE: wordpress000db
#       MYSQL_USER: wordpress000kun
#       MYSQL_PASSWORD: wkunpass

#   wordpress000ex12:  # container2의 이름
#     depends_on:  # mysql이 켜지고 나서 켜야함.(순서를 정해주는 것)
#       - mysql000ex11
#     image: wordpress  
#     networks:
#       - wordpress000net1
#     volumes:
#       - wordpress000vol12:/var/www/html
#     ports:  # 유일하게 외부에서 접근하는 포트번호
#       - 85:80
#     restart: always  
#     environment:
#       WORDPRESS_DB_HOST: mysql000ex11
#       WORDPRESS_DB_NAME: wordpress000db
#       WORDPRESS_DB_USER: wordpress000kun
#       WORDPRESS_DB_PASSWORD: wkunpass
# networks:
#   wordpress000net1:
# volumes:
#   mysql000vol11:
#   wordpress000vol12:

# ----
# version: "1"
services:
  mysql000ex11:
    image: mysql:8.0.29
    networks:
      - wordpress000net1
    volumes:
      - mysql000vol11:/var/lib/mysqld
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: wordpress000db
      MYSQL_USER: wordpress000kun
      MYSQL_PASSWORD: wkunpass

  wordpress000ex12:
    depends_on:
      - mysql000ex11
    image: wordpress
    networks:
      - wordpress000net1
    volumes:
      - wordpress000vol12:/var/www/html
    ports:
      - 85:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql000ex11
      WORDPRESS_DB_NAME: wordpress000db
      WORDPRESS_DB_USER: wordpress000kun
      WORDPRESS_DB_PASSWORD: wkunpass
networks:
  wordpress000net1:
volumes:
  mysql000vol11:
  wordpress000vol12: